kind: Deployment
apiVersion: apps/v1
metadata:
    name: abc_tech_pro
spec:
    replicas: 2
    minReadySeconds: 45
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
    selector:
        matchLabels:
            app: abc_tech_pro
    template:
        metadata:
            labels:
                app: abc_tech_pro
        spec:
            containers:
                - image: majormekzy/abc_technologies:latest
                  name: app
---

kind: Service
apiVersion: v1
metadata:
    name: abc_tech_service
spec:
    type: NodePort
    selector:
        app: abc_tech_pro
    ports:
        - port: 80 #cluster port
          targetPort: 8080 #container image port